import type { Metadata } from "next";
import { ReactQueryProvider } from "@/app/providers/react-query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header className="p-4">
          <h1 className="text-center">Star Wars!</h1>
        </header>

        <ReactQueryProvider>
          <main className="max-w-6xl mx-auto">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
