import type { Metadata } from "next";
import { ReactQueryProvider } from "@/app/providers/react-query-provider";
import "./globals.css";

import { Logo } from "@/app/components/logo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header className=" flex justify-center p-4">
          <Logo />
        </header>

        <ReactQueryProvider>
          <main className="max-w-6xl mx-auto">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
